# Main Page Setup
title: Blase Londoño's Portfolio # This is what shows up in the tab of the browser




# Hero Section
name: Blase Londoño
headline: Mechanical Engineering Undergraduate Student at UC San Diego
description: | # dont remove this line. this will ignore all new lines until the next section
  I'm drawn to engineering for the fast-paced problem-solving and the opportunity to work with talented people on challenging technical projects. Whether I'm designing power distribution systems for Mars rovers, prototyping airless tire systems, or teaching MATLAB to 35+ students, I enjoy building systems that work and collaborating with teams that push the boundaries of what's possible. <br><br>
  I'm currently involved with UCSD Yonder Dynamics, IEEE-HKN, Tau Beta Pi, Apple's Next-Gen Innovators program, and undergraduate research in semiconductor characterization. As I continue through my degree, I'm focused on finding the right area within robotics to commit to long-term and make a meaningful impact. <br><br>




# Profile image 
profile_image: /assets/images/profile-image/sm_yellow_sq.jpg




# Link resume
resume-url: /assets/resume/londono_blase_resume.pdf




# Set up external links
external-links:    # input only url slug.
  linkedin: blase-londono    # https://www.linkedin.com/in/{your url slug} 
  github: blasejlondono      # https://github.com/{your url slug} 
  stackoverflow:             # https://stackoverflow.com/users/{your url slug}
  medium:                    # https://medium.com/@{your url slug} 
  x-twitter:                 # https://x.com/{your url slug} 
  threads:                   # https://threads.net/@{your url slug} 
  instragram: blaselondono   # https://instagram.com/{your url slug} 
  youtube:                   # https://youtube.com/@{your url slug} 
  discord:                   # https://discord.com/users/{your url slug} 
  bluesky:                   # https://bsky.app/profile/{your url slug} 




# Skills Section
skills:
  - category: CAD & Modeling
    tools:
    - OnShape
    - Autodesk Fusion360
    - Autodesk AutoCAD
    
  - category: Prototyping & Fabrication
    tools:
    - 3D Printing
    - Laser Cutting
    - CNC Machining
    - Hand Sketching
    - Drilling
    - Tapping
    - Reaming
    - Press Fitting
    
  - category: Electronics & PCB Design
    tools:
    - Altium Designer
    - Arduino
    - Linear Circuit Design
    - Soldering
    - Crimping
    - Splicing
    - Breadboarding
    - Protoboarding
    
  - category: Programming
    tools:
    - MATLAB
    - Python
    - Java
    - Arduino C
    - HTML
    - CSS
    - Git
    
  - category: Visual Design
    tools:
    - Canva
    - LaTeX
    - GIMP
    - InkScape




# Active theme 
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"




#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.
collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/